---
   - name: Create helloworld user and Group
    user:
      name: helloworld
      comment: user for helloworld
	  
  - name: Copy gs-spring-boot from local to remote
    copy:
      src: gs-spring-boot
      dest: /opt
      mode: 0755

  - name: Change owner ship for helloworld
    file:
      path: /opt/gs-spring-boot-{{ version }}.jar
      owner: helloworld
      group: helloworld
      mode: '0755'
	  
  - name: Create the soft link from old to new version
    file:
      src: /opt/gs-spring-boot-{{ version }}.jar
      dest: "/opt/gs-spring-boot.jar"
      state: link

  - name : helloworld template
    template:
      src: helloworld.service.j2
      dest: ./helloworld.service

  - name: Copy helloworld service from local to remote
    copy:
      src: /root/helloworld.service
      dest: /etc/systemd/system/
      mode: 0755
      remote_src: yes

  - name: just force systemd to reread configs (2.4 and above)
    systemd:
      daemon_reload: yes
